package report;

import model.ProductSale;
import service.SalesCalculator;

import java.util.List;
import java.util.Map;

public class SalesReport {

    // Generates a formatted sales summary report from the product sales data.
    public String generate(List<ProductSale> sales) {
        SalesCalculator calculator = new SalesCalculator();
        StringBuilder report = new StringBuilder();

        appendHeader(report);
        appendProductRevenue(report, sales, calculator);
        appendCategoryRevenue(report, sales, calculator);
        appendHighlights(report, sales, calculator);
        appendFooter(report);

        return report.toString();
    }

    // Adds the report header.
    private void appendHeader(StringBuilder report) {
        report.append("============================================\n");
        report.append(" PRODUCT SALES SUMMARY REPORT\n");
        report.append("============================================\n");
    }

    // Adds revenue details for each product to the report.
    private void appendProductRevenue(
            StringBuilder report,
            List<ProductSale> sales,
            SalesCalculator calculator) {

        report.append("--- Revenue Per Product ---\n");

        for (ProductSale sale : sales) {
            report.append(String.format(
                    "%-5s %-20s %-12s $%8.2f%n",
                    sale.getProductId(),
                    sale.getProductName(),
                    sale.getCategory(),
                    calculator.calculateRevenue(sale)
            ));
        }
    }

    // Adds the total revenue generated by each category.
    private void appendCategoryRevenue(
            StringBuilder report,
            List<ProductSale> sales,
            SalesCalculator calculator) {

        report.append("--- Revenue Per Category ---\n");

        for (Map.Entry<String, Double> entry :
                calculator.revenuePerCategory(sales).entrySet()) {

            report.append(String.format(
                    "%-12s : $%.2f%n",
                    entry.getKey(),
                    entry.getValue()
            ));
        }
    }

    // Adds key sales highlights to the report.
    private void appendHighlights(
            StringBuilder report,
            List<ProductSale> sales,
            SalesCalculator calculator) {

        ProductSale best = calculator.bestSellingProduct(sales);
        ProductSale highest = calculator.highestRevenueProduct(sales);

        report.append("--- Highlights ---\n");

        if (best != null) {
            report.append(String.format(
                    "%-23s : %s (%d units)%n",
                    "Best Selling Product",
                    best.getProductName(),
                    best.getQuantitySold()
            ));
        }

        if (highest != null) {
            report.append(String.format(
                    "%-23s : $%.2f%n",
                    "Highest Revenue",
                    calculator.calculateRevenue(highest)
            ));
        }

        // Adds the total revenue from all products.
        report.append(String.format(
                "%-23s : $%.2f%n",
                "Grand Total Revenue",
                calculator.grandTotalRevenue(sales)
        ));
    }

    // Adds the report footer.
    private void appendFooter(StringBuilder report) {
        report.append("============================================\n");
    }
}