package model;

public class ProductSale {

    // Stores the details of a single product sale.
    private final String productId;
    private final String productName;
    private final String category;
    private final int quantitySold;
    private final double unitPrice;

    // Creates a product sale with its identifying and sales information.
    public ProductSale(String productId, String productName, String category,
                       int quantitySold, double unitPrice) {
        this.productId = productId;
        this.productName = productName;
        this.category = category;
        this.quantitySold = quantitySold;
        this.unitPrice = unitPrice;
    }

    // Returns the unique product identifier.
    public String getProductId() {
        return productId;
    }

    // Returns the product name.
    public String getProductName() {
        return productName;
    }

    // Returns the product category.
    public String getCategory() {
        return category;
    }

    // Returns the quantity of the product sold.
    public int getQuantitySold() {
        return quantitySold;
    }

    // Returns the unit price of the product.
    public double getUnitPrice() {
        return unitPrice;
    }

    // Calculates the revenue generated by this product.
    public double getRevenue() {
        return quantitySold * unitPrice;
    }
}