package service;

import model.ProductSale;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class SalesCalculator {

    // Calculates the revenue generated by a single product.
    public double calculateRevenue(ProductSale product) {
        return product.getRevenue();
    }

    // Calculates the total revenue for each product category.
    public Map<String, Double> revenuePerCategory(List<ProductSale> sales) {
        Map<String, Double> result = new LinkedHashMap<>();

        for (ProductSale sale : sales) {
            result.merge(
                    sale.getCategory(),
                    calculateRevenue(sale),
                    Double::sum
            );
        }

        return result;
    }

    // Finds and returns the product with the highest quantity sold.
    public ProductSale bestSellingProduct(List<ProductSale> sales) {
        if (sales == null || sales.isEmpty()) {
            return null;
        }

        ProductSale best = sales.get(0);

        for (ProductSale sale : sales) {
            if (sale.getQuantitySold() > best.getQuantitySold()) {
                best = sale;
            }
        }

        return best;
    }

    // Finds and returns the product that generated the highest revenue.
    public ProductSale highestRevenueProduct(List<ProductSale> sales) {
        if (sales == null || sales.isEmpty()) {
            return null;
        }

        ProductSale highest = sales.get(0);

        for (ProductSale sale : sales) {
            if (calculateRevenue(sale) > calculateRevenue(highest)) {
                highest = sale;
            }
        }

        return highest;
    }

    // Calculates the total revenue generated by all products.
    public double grandTotalRevenue(List<ProductSale> sales) {
        double total = 0.0;

        for (ProductSale sale : sales) {
            total += calculateRevenue(sale);
        }

        return total;
    }
}